name: share_scooter
description: "A new Flutter project."

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=3.5.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  flutter_map_geojson : ^1.0.5
  cupertino_icons: ^1.0.6
  flutter_map: ^6.1.0
  latlong2: ^0.9.0
  geolocator: ^10.1.0
  flutter_svg: ^2.0.8
  http: ^1.2.1
  flutter_map_location_marker: any # or latest verion
  flutter_map_tile_caching: ^9.0.1
  qr_code_scanner: ^1.0.1
  shared_preferences: ^2.2.3
  uuid: ^4.4.0
  get_it: ^7.7.0
  bloc: ^8.1.4
  flutter_bloc: ^8.1.5
  equatable: ^2.0.5
  flutter_map_cancellable_tile_provider: ^2.0.0
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  shamsi_date: ^1.0.2
  dio: ^5.5.0+1
  rxdart: ^0.28.0
  internet_connection_checker: ^1.0.0+1
  flutter_animate: ^4.5.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: ^2.4.9
  hive_generator: ^2.0.1
  flutter_lints: ^3.0.0

flutter:


  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/icons/
    - assets/images/

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  fonts:
    - family: Vazir
      fonts:
        - asset: assets/font/Vazir-Regular.ttf
          weight: 500
        - asset: assets/font/Vazir-Medium.ttf
          weight: 600
        - asset: assets/font/Vazir-Bold.ttf
          weight: 700
        - asset: assets/font/Vazir-Light.ttf
          weight: 400
        - asset: assets/font/Vazir-Thin.ttf
          weight: 300 

  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages